name: Miniaturise
version: '${project.version}'
main: de.leghast.miniaturise.Miniaturise
api-version: '1.20'
authors: [GhastCraftHD]
description: A tool which lets you create miniatures of your builds and makes working with block displays easy (Idea by reyzixDE)
website: https://www.github.com/LeGhast/Miniaturise
commands:
  mselect:
    aliases: msel
    description: Selects the region, if you have selected the two corner locations. Also selects any placed miniatures, that are in the defined region
  mscale:
    description: Scales either the miniature in the clipboard or the selected placed miniature
  mcut:
    description: Cuts the selected region (blocks) from the world
  mtools:
    description: Lists up all tools and what item they are bound to
  mpaste:
    description: Pastes the miniature from the clipboard to the world
  mdelete:
    description: Deletes the selected placed miniature
  mcopy:
    description: Copies the placed miniatures from the region, if you have selected the two corner locations.
  mposition:
    aliases : mpos
    description: Sets the corner position of a selectable region
  mclear:
    description: Clears your clipboard
  madjust:
    description: Opens the settings for the adjuster tool
  mrotate:
    description: Rotates the selected placed miniature

permissions:
  miniaturise.use:
    default: true
    description: The permission that lets you use Miniaturise